apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jupyterhub-cost-monitoring.resourceName" . }}-deployment
  labels:
    {{- include "jupyterhub-cost-monitoring.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "jupyterhub-cost-monitoring.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/service-account: {{ include (print .Template.BasePath "/serviceaccount.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- . | toYaml | nindent 8 }}
        {{- end }}
      labels:
        {{- include "jupyterhub-cost-monitoring.labels" . | nindent 8 }}
    spec:
      volumes:
        - name: secret
          secret:
            secretName: {{ include "jupyterhub-cost-monitoring.webserver.fullname" . }}
      containers:
        - name: webserver
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{- with .Values.image.pullPolicy }}
          imagePullPolicy: {{ . }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            {{- with .Values.extraEnv }}
            {{- tpl (. | toYaml) $ | nindent 12 }}
            {{- end }}
          resources:
            {{- .Values.resources | toYaml | nindent 12 }}
          securityContext:
            {{- .Values.securityContext | toYaml | nindent 12 }}
          startupProbe:
            periodSeconds: 1
            failureThreshold: 60
            httpGet:
              path: /health/ready
              port: http
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with include "jupyterhub-cost-monitoring.webserver.serviceaccount.fullname" . }}
      serviceAccountName: {{ . }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
