kind: Secret
apiVersion: v1
metadata:
  name: {{ include "jupyterhub-cost-monitoring.resourceName" . }}
  labels: {{- include "jupyterhub-cost-monitoring.labels" . | nindent 4 }}
type: Opaque
stringData:
  jupyterhub_cost_monitoring_config.json: {{ .Values.config | toJson | quote }}
