apiVersion: v1
kind: Service
metadata:
  name: {{ include "jupyterhub-cost-monitoring.webserver.fullname" . }}
  labels: {{- include "jupyterhub-cost-monitoring.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      {{- with .Values.service.nodePort }}
      nodePort: {{ . }}
      {{- end }}
  selector: {{- include "jupyterhub-cost-monitoring.selectorLabels" . | nindent 4 }}
