# General configuration
# -----------------------------------------------------------------------------
#
nameOverride: ''
fullnameOverride: ''
global: {}

# Deployment resource
# -----------------------------------------------------------------------------
#
replicas: 1
extraEnv: []
image:
  repository: quay.io/2i2c/jupyterhub-cost-monitoring
  tag: set-by-chartpress
  pullPolicy: ''
  pullSecrets: []
resources: {}
securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65534 # nobody user
  runAsGroup: 65534 # nobody group

podSecurityContext: {}
podAnnotations: {}
nodeSelector: {}
affinity: {}
tolerations: []

# ServiceAccount resource
# -----------------------------------------------------------------------------
#
serviceAccount:
  create: true
  name: ''
  annotations: {}

# Service resource
# -----------------------------------------------------------------------------
#
service:
  type: ClusterIP
  port: 80

# Ingress resource
# -----------------------------------------------------------------------------
#
ingress:
  enabled: false
  annotations: {}
  ingressClassName:
  hosts: []
  pathSuffix:
  pathType: Prefix
  tls: []

# NetworkPolicy resource
# -----------------------------------------------------------------------------
#
networkPolicy:
  enabled: true
  ingress: []
  ingressAllowRules:
    localGrafanaInstances: true
