nameOverride: ''
fullnameOverride: ''
global: {}

replicas: 1
extraEnv: []
image:
  repository: quay.io/2i2c/jupyterhub-cost-monitoring
  tag: set-by-chartpress
  pullPolicy: ''
  pullSecrets: []
resources: {}
securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65534 # nobody user
  runAsGroup: 65534 # nobody group

podSecurityContext: {}
podAnnotations: {}
nodeSelector: {}
affinity: {}
tolerations: []

serviceAccount:
  create: true
  name: ''
  annotations: {}

service:
  type: ClusterIP
  port: 80
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"

ingress:
  enabled: false
  annotations: {}
  ingressClassName:
  hosts: []
  pathSuffix:
  pathType: Prefix
  tls: []

networkPolicy:
  enabled: true
  ingress: []
  ingressAllowRules:
    localGrafanaInstances: true

prometheusAuth:
  enabled: false
  envFromSecret: ""
