name: Run tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Setup python
      uses: actions/setup-python@v7
      with:
        python-version: "3.13"

    - name: Install package + dev dependencies
      run: |
        pip install --editable ".[dev]"

    - name: Run tests
      run: |
        py.test tests/
